[tool.flit.metadata]
module="{{ cookiecutter.package_import_name }}"
author="{{ cookiecutter.author_fullname }}"
author-email="{{ cookiecutter.author_email }}"
home-page="https://{{ cookiecutter.repository_provider }}/{{ cookiecutter.repository_namespace }}/{{ cookiecutter.repository_name }}"
requires=[]
requires-python="3"
# description-file="README.rst"  # FIXME: ../README.md
classifiers=[
    # http://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Intended Audience :: Developers",
    # "License :: OSI Approved :: ISC License (ISCL)",  # FIXME
    "Development Status :: 3 - Alpha",
    "Operating System :: Unix",
    {% if cookiecutter.framework_django|lower == "yes" -%}"Framework :: Django",{%- endif %}
    "Programming Language :: Python :: 3",
    'Topic :: Utilities',
]

{% if cookiecutter.package_uses_cli -%}
[tool.flit.entrypoints."console_scripts"]
{{ cookiecutter.package_cli_name }} = "{{ cookiecutter.package_import_name }}.cli:main"
{%- endif %}
